Chapter 4: Getting started
amolenk/docs pull request #14
Opened 2020-12-04 16:03 UTC by amolenk

WIP for chapter 4

2020-12-16 11:25 UTC, amolenk commented
@robvet @EdwinVW Chapter 4 is now ready for internal review.

2020-12-23 19:33 UTC, EdwinVW requested changes
Internal review

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +4. Add a second project to the same solution and call it *DaprBackEnd*. Select **API** as the project type, and clear the checkbox for **Configure for HTTPS**. It's recommended to deploy Dapr sidecar
```suggestion
4. Add a second ASP.NET Core Web Application project to the same solution and call it *DaprBackEnd*. Select **API** as the project type, and clear the checkbox for **Configure for HTTPS**. It's recommended to deploy Dapr sidecars in the same network namespace as the application. Therefore, the Dapr sidecar is designed to use unencrypted HTTP to communicate with the application. Note that we still use HTTPS for the front-end and that Dapr provides support for mTLS to encrypt calls between services.
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   ![walkthrough-multicontainer-addpackage](/Users/sander/Git/DaprBook/MSArchDocsFork/docs/architecture/dapr-for-net-developers/media/ch4-getting-started/walkthrough-multicontainer-addpackage.png)
Path is not correct (links to a local file on your machine).
Also I would show the command in text (remove the screenshot) so readers can copy/paste it into the console.

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   ![Screenshot of adding a new C# class](./media/ch4-getting-started/walkthrough-multicontainer-addmodel.png)
Screenshot is not necessary i.m.o.

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   Replace the template with the following code:
```suggestion
   Replace the content of the file with the following code:
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +4. Open the *Index.cshtml.cs* file, and replace its contents with the following code:
```suggestion
4. Open the *Index.cshtml.cs* file in the *Pages* folder, and replace its contents with the following code:
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   Note that the `DaprClient` is injected into the `IndexModel` constructor. The `OnGet` method gets called when the user visits the home page. Here we use the injected `DaprClient` instance to invok
```suggestion
   Note that the `DaprClient` is injected into the `IndexModel` constructor. The `OnGet` method gets called when the user visits the home page. Here we use the injected `DaprClient` instance to invoke the `weatherforecast` method of the `daprbackend` service. You'll configure the back-end web API to use `daprbackend` as its application id later on when running it with Dapr. Finally, the service response is saved in view data.
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +5. In the *Index.cshtml* file, add the code to display the weather forecasts stored in the view data to the user:
```suggestion
5. Replace the contents of the *Index.cshtml* file in the *Pages* folder, with the following code. It displays the weather forecasts stored in the view data to the user:
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +1. In the `DaprFrontEnd` project, choose **Add > Container Orchestrator Support**. The **Add Container Orchestrator Support** dialog appears:
```suggestion
1. Right-click the `DaprFrontEnd` project, and choose **Add > Container Orchestrator Support**. The **Add Container Orchestrator Support** dialog appears:
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   Visual Studio creates a *docker-compose.yml* file and a *.dockerignore* file in the **docker-compose** node in the solution:
```suggestion
   Visual Studio creates a *docker-compose.yml* file and a *.dockerignore* file in the **docker-compose** folder in the solution:
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   The *docker-compose.yml* file has the following content:
If you're not explaining anything about the contents of the `docker-compose.yml`, I would leave this and the snippet out. Readers can just open the file if they are interested in the contents.

```suggestion
   Open the *docker-compose.yml* file and examine its contents.
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   Visual Studio makes some changes to your Compose file. Now both services are included:
```suggestion
   Open the *docker-compose.yml* file again and examine its contents. Visual Studio has made some changes to your Compose file. Now both services are included.
```

Leave out the snippet.

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   - The gRPC listening ports of the Dapr sidecars must be exposed for the sidecars to communicate with each other.
```suggestion
   - The ports that the Dapr sidecars are listening on for gRPC communication (by default 50001), must be exposed to allow the sidecars to communicate with each other.
```

2020-12-23 19:33 UTC, EdwinVW commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +5. Run the solution (**F5** or **Ctrl+F5**) to verify that it works as expected. If everything is configured correctly, you see the weather forecast data:
```suggestion
5. Run the solution (**F5** or **Ctrl+F5**) to verify that it works as expected. If everything is configured correctly, you should see the weather forecast data:
```

2020-12-30 14:55 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   > By default, Dapr uses Docker containers to give you the best out-of-the-box experience. If you want to install Dapr locally without requiring Docker, you can skip these steps and [execute a *sli
I'm keeping the indentation because that ensures that the note is rendered as part of step 2 in the list.

2020-12-30 14:57 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +In the previous section, you've created a stateful application which uses the default state store component installed by Dapr. When you initialize Dapr using the `dapr init` command, the Dapr CLI aut
I'm going to keep calling it a `state store component`. The Dapr docs do the same. They refer to the building block and concept as 'state management'. But then they talk about 'pluggable state stores' and 'state store components'.

2021-01-06 15:11 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   ~$ dotnet new console -o DaprCounter
Removed the prompts.

2021-01-06 15:13 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +- [.NET Core 3 Development Tools](https://dotnet.microsoft.com/download/dotnet-core/3.1) for development with .NET Core 3.
Mentioned Docker Desktop

2021-01-06 16:43 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   ![walkthrough-multicontainer-addpackage](/Users/sander/Git/DaprBook/MSArchDocsFork/docs/architecture/dapr-for-net-developers/media/ch4-getting-started/walkthrough-multicontainer-addpackage.png)
Replaced screenshot with code snippet

2021-01-06 16:44 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   ![Screenshot of adding a new C# class](./media/ch4-getting-started/walkthrough-multicontainer-addmodel.png)
Removed screenshot.

2021-01-06 16:47 UTC, amolenk commented on docs/architecture/dapr-for-net-developers/ch4-getting-started.md
> +   The *docker-compose.yml* file has the following content:
Reworded it slightly. Still want to show it because I'm also showing how it changed a little bit later on.

2021-01-06 16:47 UTC, amolenk commented
Closing this PR because I need to renumber the chapter.

2021-01-06 16:47 UTC, closed without merging